---
collections:
  - name: https://github.com/usegalaxy-eu/ansible-collection-handy
    type: git
    version: c3c1d67bf7bfc462edb30a39c14432f431c24275
  - name: ansible.posix
    version: 1.5.1
    source: https://galaxy.ansible.com
  - name: amazon.aws
    version: 1.5.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: devsec.hardening
    version: 10.5.2
    source: https://galaxy.ansible.com
    type: galaxy
roles:
  - name: usegalaxy_eu.cuda
    version: 7d272fa51d7f8297dd7dd49856934a22fc12d208 # CHANGE ME
    src: https://github.com/usegalaxy-eu/ansible-cuda
  - name: usegalaxy_eu.nvidia_container
    src: https://github.com/usegalaxy-eu/ansible-nvidia-container
    version: 7c608da6f512d16e7e9e772e41d8ae9d1fa0a724
  - src: geerlingguy.docker
    version: 8.0.0
  - src: https://github.com/usegalaxy-eu/ansible-chrony
    name: influxdata.chrony
    version: 0.1.1
  - src: galaxyproject.pulsar
    version: 1.0.10
  - src: https://github.com/usegalaxy-eu/ansible-dynmotd
    name: usegalaxy-eu.dynmotd
    version: 0.0.1
  - name: grycap.htcondor
    src: https://github.com/usegalaxy-eu/ansible-htcondor-grycap
    version: fe15ce1569e93a9d1030350c42d1af79e8c3e905
  - src: geerlingguy.repo-epel
    version: 3.1.0
  - src: geerlingguy.java
    version: 2.6.1
  - src: https://github.com/gsaudade99/ansible-cvmfs # Point to my fix
    name: galaxyproject.cvmfs
    version: d2e813a501be074af09e815bf86749e8ab38bed0
  - src: https://github.com/usegalaxy-eu/ansible-autofs
    name: usegalaxy-eu.autofs
    version: 08a15b6e9b031bed659fd718b036b4b8c387bb35
  - name: usegalaxy-eu.autoupdates
    src: https://github.com/usegalaxy-eu/ansible-autoupdates
    version: 0.0.1
  - name: usegalaxy-eu.fslimit
    src: https://github.com/usegalaxy-eu/ansible-fslimit
    version: main
  - name: usegalaxy-eu.telegraf
    src: https://github.com/dj-wasabi/ansible-telegraf
    version: 0.14.1
  - name: galaxyproject.miniconda
    src: https://github.com/galaxyproject/ansible-miniconda
    version: 0.3.1
  - name: openslx-ng.dracut
    src: https://github.com/usegalaxy-eu/ansible-dracut
    version: 0.0.1
