---
collections:
  - name: usegalaxy_eu.handy
    version: 3.0.1
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.5.1
    source: https://galaxy.ansible.com
  - name: amazon.aws
    version: 1.5.0
    source: https://galaxy.ansible.com
    type: galaxy
roles:
  - src: usegalaxy_eu.cuda
    version: 1.1.0
  - src: usegalaxy_eu.nvidia_container
    version: 1.2.0
  - src: geerlingguy.docker
    version: 6.1.0
  - src: https://github.com/usegalaxy-eu/ansible-chrony
    name: influxdata.chrony
    version: 0.1.1
  - src: galaxyproject.pulsar
    version: 1.0.10
  - src: https://github.com/usegalaxy-eu/ansible-dynmotd
    name: usegalaxy-eu.dynmotd
    version: 0.0.1
  - name: grycap.htcondor
    src: https://github.com/kysrpex/grycap-ansible-role-htcondor.git
    version: d9a4aab0052dfb31d48c986d39a7f5e3692abba4
  - src: geerlingguy.repo-epel
    version: 3.1.0
  - src: geerlingguy.java
    version: 2.2.0
  - src: galaxyproject.cvmfs
    version: 0.2.21
  - src: https://github.com/usegalaxy-eu/ansible-autofs
    name: usegalaxy-eu.autofs
    version: 1.1.1
  - name: usegalaxy-eu.autoupdates
    src: https://github.com/usegalaxy-eu/ansible-autoupdates
    version: 0.0.1
  - name: usegalaxy-eu.fslimit
    src: https://github.com/usegalaxy-eu/ansible-fslimit
    version: main
  - name: usegalaxy-eu.telegraf
    src: https://github.com/dj-wasabi/ansible-telegraf
    version: 0.14.1
  - name: galaxyproject.miniconda
    src: https://github.com/galaxyproject/ansible-miniconda
    version: 0.3.1

