#!/usr/bin/env python
#
# Everyone's got their Q&D pretty-printer for JSON files and this is mine...
#

import sys
import json
import pprint

def pprint_file_json(fname):
    """Pretty-print contents of JSON file FNAME to stdout."""
    try:
        with open(fname, 'r') as f:
            obj = json.load(f)
            pprint.pprint(obj)
    except IOError, e:
        sys.stderr.write("I/O error(%d): %s\n" % (e.errno, e.strerror))
    except ValueError, e:
        sys.stderr.write("Invalid input: %s\n" % e)

def main():
    """Main entry point for script mode."""
    if len(sys.argv) == 2:
        pprint_file_json(sys.argv[1])
    else:
        sys.stderr.write("Usage: %s FILE\n" % sys.argv[0])
        sys.exit(1)

if __name__ == "__main__":
    main()

