# Setup for Virtual Galaxy Compute Node
# This setup is valid for RHEL 9.x based systems.
# It has SELinux permissive and firewalld enabled
---
- name: Setup VGCN compute node
  hosts: default
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/grub.yml"
    - "group_vars/pulsar.yml"
    - "group_vars/condor.yml"
  pre_tasks:
    - name: System update
      ansible.builtin.dnf:
        name: "*"
        state: latest
        exclude: condor*
    - name: Install Pulsar dependencies
      ansible.builtin.package:
        name:
          - git
          - python3-virtualenv
          - python3
          - python3-pycurl
          - python3-devel
          - yum
          - gcc
          - curl
          - libcurl-devel
          - python3-libs
          - python38
          - python38-devel
          - openssl
          - openssl-devel
        state: present
      become: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 8
    - name: Install Pulsar dependencies
      ansible.builtin.package:
        name:
          - git
          - libcurl-devel
          - python-devel
        state: present
      become: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 9
    - name: Set default version of Python
      community.general.alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
    - name: Set SELINUX to permissive
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=permissive
    - name: "Deploy docker-stop-1M script"
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          docker ps -f status=running --format '{{ '{{' }}.ID}}: {{ '{{' }}.RunningFor}}' | awk '/months/ && $2 > 1 { print $0 }'|cut -f1 -d':' | xargs docker stop
        dest: /usr/bin/docker-stop-1M
        owner: root
        group: root
        mode: '0755'
  post_tasks:
    - name: Add firewall rules for NFS
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - nfs
        - rpc-bind
        - mountd
    - name: Open Port for HTCondor
      ansible.posix.firewalld:
        port: 9618/tcp
        state: enabled
        permanent: true
        immediate: true
    - name: Restart Autofs
      ansible.builtin.service:
        name: autofs
        state: restarted
    - name: Add groups to Galaxy user
      ansible.builtin.user:
        name: galaxy
        groups: condor,docker
        append: true
    - name: Remove packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - gcc
          - libcurl-devel
          - openssl-devel
      become: true
    - name: Ensure Docker directory extists
      ansible.builtin.file:
        state: directory
        path: /etc/docker
        mode: '0755'
    - name: Copy Docker daemon.json
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'
    - name: Restart Docker service, in all cases
      ansible.builtin.service:
        name: docker
        state: restarted
    - name: Deploy a signal emitter for telegraf
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo '{"alive":1}'
        dest: /bin/iamalive
        owner: telegraf
        group: telegraf
        mode: '0755'
  roles:
    - geerlingguy.repo-epel # Install EPEL
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_powertools: true # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_remap_user: true
        enable_kernel_5: true
        enable_pam_limits: true
        enable_grub: true
        enable_cgroups: "{{ false if ansible_facts['distribution_major_version'] == '9' else true }}"
        enable_journald: true
        enable_install_software: true
        enable_ansible_root_cron: false
        enable_create_user: true

    - usegalaxy-eu.autofs
    - usegalaxy-eu.dynmotd
    - geerlingguy.java
    - geerlingguy.docker
    - influxdata.chrony
    - usegalaxy-eu.telegraf
    - galaxyproject.cvmfs
    - galaxyproject.pulsar
    - usegalaxy-eu.logrotate

    # Applies a 250GB soft and 1TB hard limit on the file size for the condor systemd unit
    - role: usegalaxy-eu.fslimit
      become: true
      vars:
        ulimit_fsize_unit: "condor.service"
        ulimit_fsize_soft: 268435456000
        ulimit_fsize_hard: 1073741824000
