# Setup for Virtual Galaxy Compute Node
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/pulsar.yml"
    - "group_vars/condor.yml"

  roles:
    - galaxy
    - basic
    - htcondor
    - systemupdate
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
    - CyVerse-Ansible.singularity
    - geerlingguy.java
    - geerlingguy.docker
    - cvmfs
    - galaxyproject.pulsar
