# REMOVE ME PLEASE; THIS WAS JUST A TEST
---
- name: Debug SSH key ownership
  hosts: all
  tasks:
    - name: Get owner and group for (private) SSH host keys
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ed25519_key
      register: ssh_host_keys_stat

    - name: Debug SSH host key ownership
      ansible.builtin.debug:
        var: ssh_host_keys_stat

    - name: Assert SSH host keys are owned by `ssh_keys` and have correct permissions
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int <= 9
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.pw_name == "root"
          - item.stat.gr_name == "ssh_keys"
          - item.stat.mode == "0640"
      loop: "{{ ssh_host_keys_stat.results }}"

    - name: Assert SSH host keys are owned by root and have correct permissions
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 10
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.pw_name == "root"
          - item.stat.gr_name == "root"
          - item.stat.mode == "0600"
      loop: "{{ ssh_host_keys_stat.results }}"
