---
- hosts: internal
  vars:
    internal: true
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/condor.yml"
  pre_tasks:
    - name: Debug Kernel version
      ansible.builtin.shell:
        cmd: uname -r
      register: kernel
    - name: Print kernel version
      ansible.builtin.debug:
        msg: "{{ kernel }}"
    - name: Include secret vars
      ansible.builtin.include_vars: "secret_group_vars/internal.yml"
      when: "'internal' in group_names"
    - name: Copy signed ssh public keys
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/ssh/
        mode: 0644
        owner: root
        group: root
      with_items:
        - ssh_host_ecdsa_key.pub
        - ssh_host_ed25519_key.pub
        - ssh_host_rsa_key.pub
        - ssh_host_ecdsa_key-cert.pub
        - ssh_host_ed25519_key-cert.pub
        - ssh_host_rsa_key-cert.pub
    - name: Copy signed ssh private keys
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/ssh/
        mode: 0600
        owner: root
        group: root
      with_items:
        - ssh_host_ecdsa_key
        - ssh_host_ed25519_key
        - ssh_host_rsa_key
      no_log: true
    - name: Add HostCertificate options
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^HostKey /etc/ssh/ssh_host_{{ item }}_key"
        line: "HostKey /etc/ssh/ssh_host_{{ item }}_key\nHostCertificate /etc/ssh/ssh_host_{{ item }}_key-cert.pub"
      with_items:
        - rsa
        - ecdsa
        - ed25519
    - name: Add core limit
      community.general.pam_limits:
        domain: galaxy
        limit_type: hard
        limit_item: core
        value: 0
  tasks:
    - ansible.builtin.include_role:
        name: cloudinit
      when: "not ('pxe' in group_names or 'kvm' in group_names)"
    - ansible.builtin.include_role:
        name: cloudinit-pxe
      when: "'pxe' in group_names"
  roles:
    - lock-root
