---
- hosts: kvm
  vars_files:
    - secret_group_vars/kvm.yml
  tasks:
    - name: Set serial getty link
      ansible.builtin.file:
        state: link
        src: /lib/systemd/system/serial-getty@.service
        dest: /etc/systemd/system/getty.target.wants/serial-getty@ttyS0.service
