---
- hosts: kvm
  vars_files:
    - secret_group_vars/kvm.yml
  post_tasks:
    - name: Enable and start serial-getty on ttyS0
      ansible.builtin.systemd:
        name: serial-getty@ttyS0.service
        enabled: yes
        state: started
    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ kvm_root_password | password_hash('sha512') }}"
  roles:
     - devsec.hardening.ssh_hardening
     - usegalaxy_eu.ssh_manager
