---
- hosts: pxe
  vars_files:
    - group_vars/pxe.yml
  pre_tasks:
    - name: Debug Kernel version
      ansible.builtin.shell:
        cmd: uname -r
      register: kernel
    - name: Print kernel version
      ansible.builtin.debug:
        msg: "{{ kernel }}"
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
    - name: Alma|Rocky|CentOS | Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        enablerepo: devel
    - name: Remove CA (to be sure)
      ansible.builtin.file:
        state: absent
        path: /tmp/server_ca
  roles:
    - devsec.hardening.ssh_hardening
    - openslx-ng.dracut
