---
- hosts: pxe
  vars_files:
    - group_vars/pxe.yml
  pre_tasks:
    - name: Debug Kernel version
      ansible.builtin.shell:
        cmd: uname -r
      register: kernel
    - name: Print kernel version
      ansible.builtin.debug:
        msg: "{{ kernel }}"
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
    - name: Alma|Rocky|CentOS | Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
    - name: Remove CA (to be sure)
      ansible.builtin.file:
        state: absent
        path: /tmp/server_ca
  tasks:
    - name: Check CPU governor
      ansible.builtin.shell:
        cmd: 'cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'
      register: cpu_governor
    - name: Set CPU governor to schedutil
      ansible.builtin.shell:
        cmd: 'cpupower frequency-set -g schedutil'
      when: 'governor != cpu_governor.stdout'
    - name: Enable cpupower.service
      ansible.builtin.service:
        state: started
        enabled: true
        name: cpupower
  roles:
    - openslx-ng.dracut
