---
- hosts: pxe
  vars_files:
    - group_vars/pxe.yml
  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: disabled
    - name: Alma|Rocky|CentOS | Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
    - name: Remove CA
      ansible.builtin.file:
        state: absent
        path: /tmp/server_ca
  roles:
    - openslx-ng.dracut
