#! /usr/bin/perl
# based on:
# https://aweirdimagination.net/2015/02/28/better-hash-based-colors/

use feature 'say';
use strict;
use open qw(:utf8);
use utf8;
use warnings;

use File::Basename 'basename';
use Digest::SHA 'sha256_hex';
use Getopt::Long;
use bignum;


sub colorize {
    my ($bg, $color, $str) = @_;

    my $color_bg = ($color + 15) % 255;
    my $out = $bg ? "\033[48;5;${color_bg}m" : '';

    return $out . "\033[38;5;${color}m${str}\033[0m";
}

while (<>) {
    chomp;

    my $hash = sha256_hex($_);
    my $num = hex(substr($hash, 0, 2));

    say colorize 1, $num, $_;
}
